# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UishechkaD.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from paths import assets_path

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        main_window_path = assets_path
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 602)
        MainWindow.setStyleSheet("background-color: rgb(222, 222, 224);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ConvertFile = QtWidgets.QPushButton(self.centralwidget)
        self.ConvertFile.setGeometry(QtCore.QRect(10, 490, 325, 81))
        font = QtGui.QFont()
        font.setFamily("Montserrat,sans-serif")
        font.setPointSize(15)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.ConvertFile.setFont(font)
        self.ConvertFile.setStyleSheet("QPushButton {\n"
"background:#e3d5cf;\n"
"text-decoration: none;\n"
"border: 2px solid #3d6a66;\n"
"padding: 15px 30px;\n"
"margin: 10px 20px;\n"
"border-radius: 10px;\n"
"font-family: \'Montserrat\', sans-serif;\n"
"font-weight: bold;\n"
"letter-spacing: 2px;\n"
"color: #3d6a66;\n"
"}\n"
"QPushButton:hover{\n"
"background: #f0e1da;\n"
"}\n"
"QPushButton:pressed {\n"
"background: linear-gradient(45deg, rgba(30, 255, 188, 1) 25%, rgba(255, 255, 255, 1) 25%, rgba(255, 255, 255, 1) 50%, rgba(30, 255, 188, 1) 50%, rgba(30, 255, 188, 1) 75%, rgba(255, 255, 255, 1) 75%, rgba(255, 255, 255, 1));\n"
"color: #696969;\n"
"}")
        self.ConvertFile.setObjectName("ConvertFile")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 801, 81))
        self.frame.setStyleSheet("background-color: rgb(61, 106, 102);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(270, 20, 400, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat,sans-serif")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("font-family: \'Montserrat\', sans-serif;\n"
"font-weight: bold;\n"
"letter-spacing: 2px;\n"
"color: #e6e6e6;\n"
"")
        self.label.setObjectName("label")
        
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(100, 5, 71, 71))
        self.label_2.setStatusTip("")
        self.label_2.setStyleSheet("color: white;\n"
"")
        self.label_2.setLocale(QtCore.QLocale(QtCore.QLocale.Afrikaans, QtCore.QLocale.SouthAfrica))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(str(main_window_path / "filerr.png")))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(-10, 80, 811, 201))
        self.frame_2.setStyleSheet("QFrame{\n"
"border: 2px solid #3d6a66;\n"
"}\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.LoadFile = QtWidgets.QPushButton(self.frame_2)
        self.LoadFile.setGeometry(QtCore.QRect(30, 60, 310, 81))
        font = QtGui.QFont()
        font.setFamily("Montserrat,sans-serif")
        font.setPointSize(15)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.LoadFile.setFont(font)
        self.LoadFile.setStyleSheet("QPushButton {\n"
"background:#e3d5cf;\n"
"text-decoration: none;\n"
"border: 2px solid #3d6a66;\n"
"padding: 15px 30px;\n"
"margin: 10px 20px;\n"
"border-radius: 10px;\n"
"font-family: \'Montserrat\', sans-serif;\n"
"font-weight: bold;\n"
"letter-spacing: 2px;\n"
"color: #3d6a66;\n"
"}\n"
"QPushButton:hover{\n"
"background: #f0e1da;\n"
"}\n"
"QPushButton:pressed {\n"
"background: linear-gradient(45deg, rgba(30, 255, 188, 1) 25%, rgba(255, 255, 255, 1) 25%, rgba(255, 255, 255, 1) 50%, rgba(30, 255, 188, 1) 50%, rgba(30, 255, 188, 1) 75%, rgba(255, 255, 255, 1) 75%, rgba(255, 255, 255, 1));\n"
"color: #696969;\n"
"}")
        self.LoadFile.setObjectName("LoadFile")
        self.DragDropFrame = QtWidgets.QFrame(self.frame_2)
        self.DragDropFrame.setGeometry(QtCore.QRect(340, 10, 291, 171))
        self.DragDropFrame.setStyleSheet("QFrame{\n"
"border: 2px solid #2b6684;\n"
"}\n"
"QFrame:hover{\n"
"background: #e6e6e6;\n"
"}")
        self.DragDropFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.DragDropFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.DragDropFrame.setObjectName("DragDropFrame")
        self.DragDropLabel = QtWidgets.QLabel(self.DragDropFrame)
        self.DragDropLabel.setGeometry(QtCore.QRect(10, 10, 271, 151))
        self.DragDropLabel.setMinimumSize(QtCore.QSize(151, 121))
        font = QtGui.QFont()
        font.setFamily("Montserrat,sans-serif")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.DragDropLabel.setFont(font)
        self.DragDropLabel.setMouseTracking(False)
        self.DragDropLabel.setAcceptDrops(False)
        self.DragDropLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.DragDropLabel.setAutoFillBackground(False)
        self.DragDropLabel.setStyleSheet("QLabel{\n"
"color: #b8b6b6;\n"
"border: 0px solid #2b6684;\n"
"}\n"
"QLabel:hover{\n"
"background: #e6e6e6;\n"
"font-family: \'Montserrat\', sans-serif;\n"
"font-weight: bold;\n"
"letter-spacing: 2px;\n"
"color: #3d6a66;\n"
"padding-right: 20px;\n"
"}\n"
"")
        self.DragDropLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.DragDropLabel.setObjectName("DragDropLabel")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(60, 80, 41, 41))
        self.label_4.setStyleSheet("QLabel {\n"
"background:#e3d5cf;\n"
"}")
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(str(main_window_path / "tapper.png")))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(-20, 270, 821, 181))
        self.frame_3.setStyleSheet("QFrame{\n"
"border: 2px solid #3d6a66;\n"
"}\n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.SaveFile = QtWidgets.QPushButton(self.frame_3)
        self.SaveFile.setGeometry(QtCore.QRect(40, 50, 301, 81))
        font = QtGui.QFont()
        font.setFamily("Montserrat,sans-serif")
        font.setPointSize(15)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.SaveFile.setFont(font)
        self.SaveFile.setStyleSheet("QPushButton {\n"
"background:#e3d5cf;\n"
"text-decoration: none;\n"
"border: 2px solid #3d6a66;\n"
"padding: 15px 30px;\n"
"margin: 10px 20px;\n"
"border-radius: 10px;\n"
"font-family: \'Montserrat\', sans-serif;\n"
"font-weight: bold;\n"
"letter-spacing: 2px;\n"
"color: #3d6a66;\n"
"}\n"
"QPushButton:hover{\n"
"background: #f0e1da;\n"
"}\n"
"QPushButton:pressed {\n"
"background: linear-gradient(45deg, rgba(30, 255, 188, 1) 25%, rgba(255, 255, 255, 1) 25%, rgba(255, 255, 255, 1) 50%, rgba(30, 255, 188, 1) 50%, rgba(30, 255, 188, 1) 75%, rgba(255, 255, 255, 1) 75%, rgba(255, 255, 255, 1));\n"
"color: #696969;\n"
"}")
        self.SaveFile.setObjectName("SaveFile")
        self.comboBox = QtWidgets.QComboBox(self.frame_3)
        self.comboBox.setGeometry(QtCore.QRect(350, 80, 301, 21))
        font = QtGui.QFont()
        font.setStrikeOut(False)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("QComboBox{\n"
"border: 2px solid #3d6a66;\n"
"}\n"
"")
        self.comboBox.setObjectName("comboBox")
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setGeometry(QtCore.QRect(70, 70, 41, 41))
        self.label_3.setStyleSheet("QLabel{\n"
"color: #b8b6b6;\n"
"border: 0px solid #2b6684;\n"
"}\n"
"QLabel {\n"
"background:#e3d5cf;\n"
"}")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(str(main_window_path / "diskettet.png")))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(330, 490, 81, 81))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(str(main_window_path / "mekha.png")))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(460, 470, 81, 81))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap(str(main_window_path / "gear.png")))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(620, 451, 181, 161))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(str(main_window_path / "Drakyla.png")))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Конвертор для PowerGraph"))
        self.ConvertFile.setText(_translate("MainWindow", "Конвертировать"))
        self.label.setText(_translate("MainWindow", "Конвертор из .pgc в .txt"))
        self.LoadFile.setText(_translate("MainWindow", "   Выбор файла"))
        self.DragDropLabel.setText(_translate("MainWindow", " Перетащите \n"
"файл сюда"))
        self.SaveFile.setText(_translate("MainWindow", "   Сохранить в"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_MainWindow()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
